version: '3.8'

services:
  app:
    container_name: order-tracking-app
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/Order-tracking
      - JWT_SECRET=349743ffsdfn437hf43f4398fh48fh
      - JWT_EXPIRES=7d
      - NODE_ENV=development
    depends_on:
      - mongo

  mongo:
    container_name: order-tracking-mongo
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: